// Generated by gencpp from file xarm_pick_place/AddObject.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_ADDOBJECT_H
#define XARM_PICK_PLACE_MESSAGE_ADDOBJECT_H

#include <ros/service_traits.h>


#include <xarm_pick_place/AddObjectRequest.h>
#include <xarm_pick_place/AddObjectResponse.h>


namespace xarm_pick_place
{

struct AddObject
{

typedef AddObjectRequest Request;
typedef AddObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddObject
} // namespace xarm_pick_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_pick_place::AddObject > {
  static const char* value()
  {
    return "4688b67f368aa70bf4c9081a2a2d142a";
  }

  static const char* value(const ::xarm_pick_place::AddObject&) { return value(); }
};

template<>
struct DataType< ::xarm_pick_place::AddObject > {
  static const char* value()
  {
    return "xarm_pick_place/AddObject";
  }

  static const char* value(const ::xarm_pick_place::AddObject&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_pick_place::AddObjectRequest> should match 
// service_traits::MD5Sum< ::xarm_pick_place::AddObject > 
template<>
struct MD5Sum< ::xarm_pick_place::AddObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::AddObject >::value();
  }
  static const char* value(const ::xarm_pick_place::AddObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::AddObjectRequest> should match 
// service_traits::DataType< ::xarm_pick_place::AddObject > 
template<>
struct DataType< ::xarm_pick_place::AddObjectRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::AddObject >::value();
  }
  static const char* value(const ::xarm_pick_place::AddObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_pick_place::AddObjectResponse> should match 
// service_traits::MD5Sum< ::xarm_pick_place::AddObject > 
template<>
struct MD5Sum< ::xarm_pick_place::AddObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::AddObject >::value();
  }
  static const char* value(const ::xarm_pick_place::AddObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::AddObjectResponse> should match 
// service_traits::DataType< ::xarm_pick_place::AddObject > 
template<>
struct DataType< ::xarm_pick_place::AddObjectResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::AddObject >::value();
  }
  static const char* value(const ::xarm_pick_place::AddObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_ADDOBJECT_H
