// Generated by gencpp from file xarm_pick_place/ArmControl.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_ARMCONTROL_H
#define XARM_PICK_PLACE_MESSAGE_ARMCONTROL_H

#include <ros/service_traits.h>


#include <xarm_pick_place/ArmControlRequest.h>
#include <xarm_pick_place/ArmControlResponse.h>


namespace xarm_pick_place
{

struct ArmControl
{

typedef ArmControlRequest Request;
typedef ArmControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmControl
} // namespace xarm_pick_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_pick_place::ArmControl > {
  static const char* value()
  {
    return "bdae41a092f6ee8c19a55dc64ce0bff1";
  }

  static const char* value(const ::xarm_pick_place::ArmControl&) { return value(); }
};

template<>
struct DataType< ::xarm_pick_place::ArmControl > {
  static const char* value()
  {
    return "xarm_pick_place/ArmControl";
  }

  static const char* value(const ::xarm_pick_place::ArmControl&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_pick_place::ArmControlRequest> should match 
// service_traits::MD5Sum< ::xarm_pick_place::ArmControl > 
template<>
struct MD5Sum< ::xarm_pick_place::ArmControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::ArmControl >::value();
  }
  static const char* value(const ::xarm_pick_place::ArmControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::ArmControlRequest> should match 
// service_traits::DataType< ::xarm_pick_place::ArmControl > 
template<>
struct DataType< ::xarm_pick_place::ArmControlRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::ArmControl >::value();
  }
  static const char* value(const ::xarm_pick_place::ArmControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_pick_place::ArmControlResponse> should match 
// service_traits::MD5Sum< ::xarm_pick_place::ArmControl > 
template<>
struct MD5Sum< ::xarm_pick_place::ArmControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::ArmControl >::value();
  }
  static const char* value(const ::xarm_pick_place::ArmControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::ArmControlResponse> should match 
// service_traits::DataType< ::xarm_pick_place::ArmControl > 
template<>
struct DataType< ::xarm_pick_place::ArmControlResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::ArmControl >::value();
  }
  static const char* value(const ::xarm_pick_place::ArmControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_ARMCONTROL_H
