// Generated by gencpp from file xarm_pick_place/ArmControlRequest.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_ARMCONTROLREQUEST_H
#define XARM_PICK_PLACE_MESSAGE_ARMCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_pick_place
{
template <class ContainerAllocator>
struct ArmControlRequest_
{
  typedef ArmControlRequest_<ContainerAllocator> Type;

  ArmControlRequest_()
    : joints_values()  {
      joints_values.assign(0.0);
  }
  ArmControlRequest_(const ContainerAllocator& _alloc)
    : joints_values()  {
  (void)_alloc;
      joints_values.assign(0.0);
  }



   typedef boost::array<float, 6>  _joints_values_type;
  _joints_values_type joints_values;





  typedef boost::shared_ptr< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmControlRequest_

typedef ::xarm_pick_place::ArmControlRequest_<std::allocator<void> > ArmControlRequest;

typedef boost::shared_ptr< ::xarm_pick_place::ArmControlRequest > ArmControlRequestPtr;
typedef boost::shared_ptr< ::xarm_pick_place::ArmControlRequest const> ArmControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_pick_place

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31d35b8ea9c05e2d738767347cc083d4";
  }

  static const char* value(const ::xarm_pick_place::ArmControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31d35b8ea9c05e2dULL;
  static const uint64_t static_value2 = 0x738767347cc083d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_pick_place/ArmControlRequest";
  }

  static const char* value(const ::xarm_pick_place::ArmControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] joints_values\n\
";
  }

  static const char* value(const ::xarm_pick_place::ArmControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_pick_place::ArmControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_pick_place::ArmControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints_values[]" << std::endl;
    for (size_t i = 0; i < v.joints_values.size(); ++i)
    {
      s << indent << "  joints_values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_ARMCONTROLREQUEST_H
