// Generated by gencpp from file xarm_pick_place/RemoveObjects.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_REMOVEOBJECTS_H
#define XARM_PICK_PLACE_MESSAGE_REMOVEOBJECTS_H

#include <ros/service_traits.h>


#include <xarm_pick_place/RemoveObjectsRequest.h>
#include <xarm_pick_place/RemoveObjectsResponse.h>


namespace xarm_pick_place
{

struct RemoveObjects
{

typedef RemoveObjectsRequest Request;
typedef RemoveObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveObjects
} // namespace xarm_pick_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_pick_place::RemoveObjects > {
  static const char* value()
  {
    return "1c917203483ea92cdcc10db8ea0c542a";
  }

  static const char* value(const ::xarm_pick_place::RemoveObjects&) { return value(); }
};

template<>
struct DataType< ::xarm_pick_place::RemoveObjects > {
  static const char* value()
  {
    return "xarm_pick_place/RemoveObjects";
  }

  static const char* value(const ::xarm_pick_place::RemoveObjects&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_pick_place::RemoveObjectsRequest> should match 
// service_traits::MD5Sum< ::xarm_pick_place::RemoveObjects > 
template<>
struct MD5Sum< ::xarm_pick_place::RemoveObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::RemoveObjects >::value();
  }
  static const char* value(const ::xarm_pick_place::RemoveObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::RemoveObjectsRequest> should match 
// service_traits::DataType< ::xarm_pick_place::RemoveObjects > 
template<>
struct DataType< ::xarm_pick_place::RemoveObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::RemoveObjects >::value();
  }
  static const char* value(const ::xarm_pick_place::RemoveObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_pick_place::RemoveObjectsResponse> should match 
// service_traits::MD5Sum< ::xarm_pick_place::RemoveObjects > 
template<>
struct MD5Sum< ::xarm_pick_place::RemoveObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::RemoveObjects >::value();
  }
  static const char* value(const ::xarm_pick_place::RemoveObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::RemoveObjectsResponse> should match 
// service_traits::DataType< ::xarm_pick_place::RemoveObjects > 
template<>
struct DataType< ::xarm_pick_place::RemoveObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::RemoveObjects >::value();
  }
  static const char* value(const ::xarm_pick_place::RemoveObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_REMOVEOBJECTS_H
