// Generated by gencpp from file xarm_pick_place/RemoveObjectsRequest.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_REMOVEOBJECTSREQUEST_H
#define XARM_PICK_PLACE_MESSAGE_REMOVEOBJECTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_pick_place
{
template <class ContainerAllocator>
struct RemoveObjectsRequest_
{
  typedef RemoveObjectsRequest_<ContainerAllocator> Type;

  RemoveObjectsRequest_()
    : objects_id()  {
    }
  RemoveObjectsRequest_(const ContainerAllocator& _alloc)
    : objects_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _objects_id_type;
  _objects_id_type objects_id;





  typedef boost::shared_ptr< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveObjectsRequest_

typedef ::xarm_pick_place::RemoveObjectsRequest_<std::allocator<void> > RemoveObjectsRequest;

typedef boost::shared_ptr< ::xarm_pick_place::RemoveObjectsRequest > RemoveObjectsRequestPtr;
typedef boost::shared_ptr< ::xarm_pick_place::RemoveObjectsRequest const> RemoveObjectsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_pick_place

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49713b5f379c9b78330f0563a9648359";
  }

  static const char* value(const ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49713b5f379c9b78ULL;
  static const uint64_t static_value2 = 0x330f0563a9648359ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_pick_place/RemoveObjectsRequest";
  }

  static const char* value(const ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] objects_id\n\
";
  }

  static const char* value(const ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveObjectsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_pick_place::RemoveObjectsRequest_<ContainerAllocator>& v)
  {
    s << indent << "objects_id[]" << std::endl;
    for (size_t i = 0; i < v.objects_id.size(); ++i)
    {
      s << indent << "  objects_id[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objects_id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_REMOVEOBJECTSREQUEST_H
