// Generated by gencpp from file xarm_pick_place/TargetPlacePose.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_TARGETPLACEPOSE_H
#define XARM_PICK_PLACE_MESSAGE_TARGETPLACEPOSE_H

#include <ros/service_traits.h>


#include <xarm_pick_place/TargetPlacePoseRequest.h>
#include <xarm_pick_place/TargetPlacePoseResponse.h>


namespace xarm_pick_place
{

struct TargetPlacePose
{

typedef TargetPlacePoseRequest Request;
typedef TargetPlacePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TargetPlacePose
} // namespace xarm_pick_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_pick_place::TargetPlacePose > {
  static const char* value()
  {
    return "58d59f258ca9f2d2ba375d9428a7f1de";
  }

  static const char* value(const ::xarm_pick_place::TargetPlacePose&) { return value(); }
};

template<>
struct DataType< ::xarm_pick_place::TargetPlacePose > {
  static const char* value()
  {
    return "xarm_pick_place/TargetPlacePose";
  }

  static const char* value(const ::xarm_pick_place::TargetPlacePose&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_pick_place::TargetPlacePoseRequest> should match 
// service_traits::MD5Sum< ::xarm_pick_place::TargetPlacePose > 
template<>
struct MD5Sum< ::xarm_pick_place::TargetPlacePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::TargetPlacePose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPlacePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::TargetPlacePoseRequest> should match 
// service_traits::DataType< ::xarm_pick_place::TargetPlacePose > 
template<>
struct DataType< ::xarm_pick_place::TargetPlacePoseRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::TargetPlacePose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPlacePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_pick_place::TargetPlacePoseResponse> should match 
// service_traits::MD5Sum< ::xarm_pick_place::TargetPlacePose > 
template<>
struct MD5Sum< ::xarm_pick_place::TargetPlacePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::TargetPlacePose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPlacePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::TargetPlacePoseResponse> should match 
// service_traits::DataType< ::xarm_pick_place::TargetPlacePose > 
template<>
struct DataType< ::xarm_pick_place::TargetPlacePoseResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::TargetPlacePose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPlacePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_TARGETPLACEPOSE_H
