// Generated by gencpp from file xarm_pick_place/TargetPickPose.msg
// DO NOT EDIT!


#ifndef XARM_PICK_PLACE_MESSAGE_TARGETPICKPOSE_H
#define XARM_PICK_PLACE_MESSAGE_TARGETPICKPOSE_H

#include <ros/service_traits.h>


#include <xarm_pick_place/TargetPickPoseRequest.h>
#include <xarm_pick_place/TargetPickPoseResponse.h>


namespace xarm_pick_place
{

struct TargetPickPose
{

typedef TargetPickPoseRequest Request;
typedef TargetPickPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TargetPickPose
} // namespace xarm_pick_place


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_pick_place::TargetPickPose > {
  static const char* value()
  {
    return "58d59f258ca9f2d2ba375d9428a7f1de";
  }

  static const char* value(const ::xarm_pick_place::TargetPickPose&) { return value(); }
};

template<>
struct DataType< ::xarm_pick_place::TargetPickPose > {
  static const char* value()
  {
    return "xarm_pick_place/TargetPickPose";
  }

  static const char* value(const ::xarm_pick_place::TargetPickPose&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_pick_place::TargetPickPoseRequest> should match 
// service_traits::MD5Sum< ::xarm_pick_place::TargetPickPose > 
template<>
struct MD5Sum< ::xarm_pick_place::TargetPickPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::TargetPickPose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPickPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::TargetPickPoseRequest> should match 
// service_traits::DataType< ::xarm_pick_place::TargetPickPose > 
template<>
struct DataType< ::xarm_pick_place::TargetPickPoseRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::TargetPickPose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPickPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_pick_place::TargetPickPoseResponse> should match 
// service_traits::MD5Sum< ::xarm_pick_place::TargetPickPose > 
template<>
struct MD5Sum< ::xarm_pick_place::TargetPickPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_pick_place::TargetPickPose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPickPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_pick_place::TargetPickPoseResponse> should match 
// service_traits::DataType< ::xarm_pick_place::TargetPickPose > 
template<>
struct DataType< ::xarm_pick_place::TargetPickPoseResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_pick_place::TargetPickPose >::value();
  }
  static const char* value(const ::xarm_pick_place::TargetPickPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_PICK_PLACE_MESSAGE_TARGETPICKPOSE_H
