// Generated by gencpp from file xarm_driver/CallVersion.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_CALLVERSION_H
#define XARM_DRIVER_MESSAGE_CALLVERSION_H

#include <ros/service_traits.h>


#include <xarm_driver/CallVersionRequest.h>
#include <xarm_driver/CallVersionResponse.h>


namespace xarm_driver
{

struct CallVersion
{

typedef CallVersionRequest Request;
typedef CallVersionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CallVersion
} // namespace xarm_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_driver::CallVersion > {
  static const char* value()
  {
    return "bdd34b709b1964ee2118cbfc3e1ee913";
  }

  static const char* value(const ::xarm_driver::CallVersion&) { return value(); }
};

template<>
struct DataType< ::xarm_driver::CallVersion > {
  static const char* value()
  {
    return "xarm_driver/CallVersion";
  }

  static const char* value(const ::xarm_driver::CallVersion&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_driver::CallVersionRequest> should match 
// service_traits::MD5Sum< ::xarm_driver::CallVersion > 
template<>
struct MD5Sum< ::xarm_driver::CallVersionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_driver::CallVersion >::value();
  }
  static const char* value(const ::xarm_driver::CallVersionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_driver::CallVersionRequest> should match 
// service_traits::DataType< ::xarm_driver::CallVersion > 
template<>
struct DataType< ::xarm_driver::CallVersionRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_driver::CallVersion >::value();
  }
  static const char* value(const ::xarm_driver::CallVersionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_driver::CallVersionResponse> should match 
// service_traits::MD5Sum< ::xarm_driver::CallVersion > 
template<>
struct MD5Sum< ::xarm_driver::CallVersionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_driver::CallVersion >::value();
  }
  static const char* value(const ::xarm_driver::CallVersionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_driver::CallVersionResponse> should match 
// service_traits::DataType< ::xarm_driver::CallVersion > 
template<>
struct DataType< ::xarm_driver::CallVersionResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_driver::CallVersion >::value();
  }
  static const char* value(const ::xarm_driver::CallVersionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_CALLVERSION_H
