// Generated by gencpp from file xarm_driver/CallVersionResponse.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_CALLVERSIONRESPONSE_H
#define XARM_DRIVER_MESSAGE_CALLVERSIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_driver
{
template <class ContainerAllocator>
struct CallVersionResponse_
{
  typedef CallVersionResponse_<ContainerAllocator> Type;

  CallVersionResponse_()
    : version()  {
    }
  CallVersionResponse_(const ContainerAllocator& _alloc)
    : version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _version_type;
  _version_type version;





  typedef boost::shared_ptr< ::xarm_driver::CallVersionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_driver::CallVersionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CallVersionResponse_

typedef ::xarm_driver::CallVersionResponse_<std::allocator<void> > CallVersionResponse;

typedef boost::shared_ptr< ::xarm_driver::CallVersionResponse > CallVersionResponsePtr;
typedef boost::shared_ptr< ::xarm_driver::CallVersionResponse const> CallVersionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_driver::CallVersionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'xarm_driver': ['/home/xbot/catkin_ws/src/xarm/xarm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::CallVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::CallVersionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::CallVersionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a6f3c569a7ebe01c997148cb8f0f453";
  }

  static const char* value(const ::xarm_driver::CallVersionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a6f3c569a7ebe01ULL;
  static const uint64_t static_value2 = 0xc997148cb8f0f453ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_driver/CallVersionResponse";
  }

  static const char* value(const ::xarm_driver::CallVersionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string version\n\
\n\
\n\
";
  }

  static const char* value(const ::xarm_driver::CallVersionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallVersionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_driver::CallVersionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_driver::CallVersionResponse_<ContainerAllocator>& v)
  {
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_CALLVERSIONRESPONSE_H
