// Generated by gencpp from file xarm_driver/CallVersionRequest.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_CALLVERSIONREQUEST_H
#define XARM_DRIVER_MESSAGE_CALLVERSIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace xarm_driver
{
template <class ContainerAllocator>
struct CallVersionRequest_
{
  typedef CallVersionRequest_<ContainerAllocator> Type;

  CallVersionRequest_()
    : empty()  {
    }
  CallVersionRequest_(const ContainerAllocator& _alloc)
    : empty(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _empty_type;
  _empty_type empty;





  typedef boost::shared_ptr< ::xarm_driver::CallVersionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_driver::CallVersionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CallVersionRequest_

typedef ::xarm_driver::CallVersionRequest_<std::allocator<void> > CallVersionRequest;

typedef boost::shared_ptr< ::xarm_driver::CallVersionRequest > CallVersionRequestPtr;
typedef boost::shared_ptr< ::xarm_driver::CallVersionRequest const> CallVersionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_driver::CallVersionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'xarm_driver': ['/home/xbot/catkin_ws/src/xarm/xarm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::CallVersionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::CallVersionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::CallVersionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aac6c697d5414bc0fcede8c33981d0e";
  }

  static const char* value(const ::xarm_driver::CallVersionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aac6c697d5414bcULL;
  static const uint64_t static_value2 = 0x0fcede8c33981d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_driver/CallVersionRequest";
  }

  static const char* value(const ::xarm_driver::CallVersionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Empty empty\n\
\n\
================================================================================\n\
MSG: std_msgs/Empty\n\
";
  }

  static const char* value(const ::xarm_driver::CallVersionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.empty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallVersionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_driver::CallVersionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_driver::CallVersionRequest_<ContainerAllocator>& v)
  {
    s << indent << "empty: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.empty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_CALLVERSIONREQUEST_H
