// Generated by gencpp from file xarm_driver/CommandJointResponse.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_COMMANDJOINTRESPONSE_H
#define XARM_DRIVER_MESSAGE_COMMANDJOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_driver
{
template <class ContainerAllocator>
struct CommandJointResponse_
{
  typedef CommandJointResponse_<ContainerAllocator> Type;

  CommandJointResponse_()
    : success(false)  {
    }
  CommandJointResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::xarm_driver::CommandJointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_driver::CommandJointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandJointResponse_

typedef ::xarm_driver::CommandJointResponse_<std::allocator<void> > CommandJointResponse;

typedef boost::shared_ptr< ::xarm_driver::CommandJointResponse > CommandJointResponsePtr;
typedef boost::shared_ptr< ::xarm_driver::CommandJointResponse const> CommandJointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_driver::CommandJointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'xarm_driver': ['/home/xbot/catkin_ws/src/xarm/xarm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::CommandJointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::CommandJointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::CommandJointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::xarm_driver::CommandJointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_driver/CommandJointResponse";
  }

  static const char* value(const ::xarm_driver::CommandJointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const ::xarm_driver::CommandJointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandJointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_driver::CommandJointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_driver::CommandJointResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_COMMANDJOINTRESPONSE_H
