// Generated by gencpp from file xarm_driver/CommandPose.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_COMMANDPOSE_H
#define XARM_DRIVER_MESSAGE_COMMANDPOSE_H

#include <ros/service_traits.h>


#include <xarm_driver/CommandPoseRequest.h>
#include <xarm_driver/CommandPoseResponse.h>


namespace xarm_driver
{

struct CommandPose
{

typedef CommandPoseRequest Request;
typedef CommandPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandPose
} // namespace xarm_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_driver::CommandPose > {
  static const char* value()
  {
    return "0ad5c450393fff0205f2e85ec899fdbf";
  }

  static const char* value(const ::xarm_driver::CommandPose&) { return value(); }
};

template<>
struct DataType< ::xarm_driver::CommandPose > {
  static const char* value()
  {
    return "xarm_driver/CommandPose";
  }

  static const char* value(const ::xarm_driver::CommandPose&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_driver::CommandPoseRequest> should match 
// service_traits::MD5Sum< ::xarm_driver::CommandPose > 
template<>
struct MD5Sum< ::xarm_driver::CommandPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_driver::CommandPose >::value();
  }
  static const char* value(const ::xarm_driver::CommandPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_driver::CommandPoseRequest> should match 
// service_traits::DataType< ::xarm_driver::CommandPose > 
template<>
struct DataType< ::xarm_driver::CommandPoseRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_driver::CommandPose >::value();
  }
  static const char* value(const ::xarm_driver::CommandPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_driver::CommandPoseResponse> should match 
// service_traits::MD5Sum< ::xarm_driver::CommandPose > 
template<>
struct MD5Sum< ::xarm_driver::CommandPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_driver::CommandPose >::value();
  }
  static const char* value(const ::xarm_driver::CommandPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_driver::CommandPoseResponse> should match 
// service_traits::DataType< ::xarm_driver::CommandPose > 
template<>
struct DataType< ::xarm_driver::CommandPoseResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_driver::CommandPose >::value();
  }
  static const char* value(const ::xarm_driver::CommandPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_COMMANDPOSE_H
