// Generated by gencpp from file xarm_driver/CommandJoint.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_COMMANDJOINT_H
#define XARM_DRIVER_MESSAGE_COMMANDJOINT_H

#include <ros/service_traits.h>


#include <xarm_driver/CommandJointRequest.h>
#include <xarm_driver/CommandJointResponse.h>


namespace xarm_driver
{

struct CommandJoint
{

typedef CommandJointRequest Request;
typedef CommandJointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandJoint
} // namespace xarm_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::xarm_driver::CommandJoint > {
  static const char* value()
  {
    return "4db41b5b4927bdd7563885ffb68a3317";
  }

  static const char* value(const ::xarm_driver::CommandJoint&) { return value(); }
};

template<>
struct DataType< ::xarm_driver::CommandJoint > {
  static const char* value()
  {
    return "xarm_driver/CommandJoint";
  }

  static const char* value(const ::xarm_driver::CommandJoint&) { return value(); }
};


// service_traits::MD5Sum< ::xarm_driver::CommandJointRequest> should match 
// service_traits::MD5Sum< ::xarm_driver::CommandJoint > 
template<>
struct MD5Sum< ::xarm_driver::CommandJointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_driver::CommandJoint >::value();
  }
  static const char* value(const ::xarm_driver::CommandJointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_driver::CommandJointRequest> should match 
// service_traits::DataType< ::xarm_driver::CommandJoint > 
template<>
struct DataType< ::xarm_driver::CommandJointRequest>
{
  static const char* value()
  {
    return DataType< ::xarm_driver::CommandJoint >::value();
  }
  static const char* value(const ::xarm_driver::CommandJointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::xarm_driver::CommandJointResponse> should match 
// service_traits::MD5Sum< ::xarm_driver::CommandJoint > 
template<>
struct MD5Sum< ::xarm_driver::CommandJointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::xarm_driver::CommandJoint >::value();
  }
  static const char* value(const ::xarm_driver::CommandJointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::xarm_driver::CommandJointResponse> should match 
// service_traits::DataType< ::xarm_driver::CommandJoint > 
template<>
struct DataType< ::xarm_driver::CommandJointResponse>
{
  static const char* value()
  {
    return DataType< ::xarm_driver::CommandJoint >::value();
  }
  static const char* value(const ::xarm_driver::CommandJointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_COMMANDJOINT_H
