// Generated by gencpp from file xarm_driver/JointLocation.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_JOINTLOCATION_H
#define XARM_DRIVER_MESSAGE_JOINTLOCATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_driver
{
template <class ContainerAllocator>
struct JointLocation_
{
  typedef JointLocation_<ContainerAllocator> Type;

  JointLocation_()
    : gripper(0.0)
    , arm_1(0.0)
    , arm_2(0.0)
    , arm_3(0.0)
    , arm_4(0.0)
    , arm_5(0.0)
    , arm_6(0.0)  {
    }
  JointLocation_(const ContainerAllocator& _alloc)
    : gripper(0.0)
    , arm_1(0.0)
    , arm_2(0.0)
    , arm_3(0.0)
    , arm_4(0.0)
    , arm_5(0.0)
    , arm_6(0.0)  {
  (void)_alloc;
    }



   typedef double _gripper_type;
  _gripper_type gripper;

   typedef double _arm_1_type;
  _arm_1_type arm_1;

   typedef double _arm_2_type;
  _arm_2_type arm_2;

   typedef double _arm_3_type;
  _arm_3_type arm_3;

   typedef double _arm_4_type;
  _arm_4_type arm_4;

   typedef double _arm_5_type;
  _arm_5_type arm_5;

   typedef double _arm_6_type;
  _arm_6_type arm_6;





  typedef boost::shared_ptr< ::xarm_driver::JointLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_driver::JointLocation_<ContainerAllocator> const> ConstPtr;

}; // struct JointLocation_

typedef ::xarm_driver::JointLocation_<std::allocator<void> > JointLocation;

typedef boost::shared_ptr< ::xarm_driver::JointLocation > JointLocationPtr;
typedef boost::shared_ptr< ::xarm_driver::JointLocation const> JointLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_driver::JointLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_driver::JointLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'xarm_driver': ['/home/xbot/catkin_ws/src/xarm/xarm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::JointLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::JointLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::JointLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::JointLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::JointLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::JointLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_driver::JointLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfa33ef15f3f0cc9e792db497bca66aa";
  }

  static const char* value(const ::xarm_driver::JointLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfa33ef15f3f0cc9ULL;
  static const uint64_t static_value2 = 0xe792db497bca66aaULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_driver::JointLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_driver/JointLocation";
  }

  static const char* value(const ::xarm_driver::JointLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_driver::JointLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 gripper\n\
float64 arm_1\n\
float64 arm_2\n\
float64 arm_3\n\
float64 arm_4\n\
float64 arm_5\n\
float64 arm_6\n\
";
  }

  static const char* value(const ::xarm_driver::JointLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_driver::JointLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper);
      stream.next(m.arm_1);
      stream.next(m.arm_2);
      stream.next(m.arm_3);
      stream.next(m.arm_4);
      stream.next(m.arm_5);
      stream.next(m.arm_6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_driver::JointLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_driver::JointLocation_<ContainerAllocator>& v)
  {
    s << indent << "gripper: ";
    Printer<double>::stream(s, indent + "  ", v.gripper);
    s << indent << "arm_1: ";
    Printer<double>::stream(s, indent + "  ", v.arm_1);
    s << indent << "arm_2: ";
    Printer<double>::stream(s, indent + "  ", v.arm_2);
    s << indent << "arm_3: ";
    Printer<double>::stream(s, indent + "  ", v.arm_3);
    s << indent << "arm_4: ";
    Printer<double>::stream(s, indent + "  ", v.arm_4);
    s << indent << "arm_5: ";
    Printer<double>::stream(s, indent + "  ", v.arm_5);
    s << indent << "arm_6: ";
    Printer<double>::stream(s, indent + "  ", v.arm_6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_JOINTLOCATION_H
