// Generated by gencpp from file xarm_driver/MotorStatus.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_MOTORSTATUS_H
#define XARM_DRIVER_MESSAGE_MOTORSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xarm_driver
{
template <class ContainerAllocator>
struct MotorStatus_
{
  typedef MotorStatus_<ContainerAllocator> Type;

  MotorStatus_()
    : location()
    , speed()
    , load()
    , voltage()
    , temperature()
    , current()
    , error()  {
    }
  MotorStatus_(const ContainerAllocator& _alloc)
    : location(_alloc)
    , speed(_alloc)
    , load(_alloc)
    , voltage(_alloc)
    , temperature(_alloc)
    , current(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _location_type;
  _location_type location;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _speed_type;
  _speed_type speed;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _load_type;
  _load_type load;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _voltage_type;
  _voltage_type voltage;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _temperature_type;
  _temperature_type temperature;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _current_type;
  _current_type current;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::xarm_driver::MotorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_driver::MotorStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStatus_

typedef ::xarm_driver::MotorStatus_<std::allocator<void> > MotorStatus;

typedef boost::shared_ptr< ::xarm_driver::MotorStatus > MotorStatusPtr;
typedef boost::shared_ptr< ::xarm_driver::MotorStatus const> MotorStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_driver::MotorStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_driver::MotorStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'xarm_driver': ['/home/xbot/catkin_ws/src/xarm/xarm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::MotorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::MotorStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::MotorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::MotorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::MotorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::MotorStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_driver::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b35e70483b9ebb379f12dfaee0874ca1";
  }

  static const char* value(const ::xarm_driver::MotorStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb35e70483b9ebb37ULL;
  static const uint64_t static_value2 = 0x9f12dfaee0874ca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_driver::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_driver/MotorStatus";
  }

  static const char* value(const ::xarm_driver::MotorStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_driver::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] location\n\
float32[] speed\n\
float32[] load\n\
float32[] voltage\n\
float32[] temperature\n\
float32[] current\n\
uint8[] error\n\
";
  }

  static const char* value(const ::xarm_driver::MotorStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_driver::MotorStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
      stream.next(m.speed);
      stream.next(m.load);
      stream.next(m.voltage);
      stream.next(m.temperature);
      stream.next(m.current);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_driver::MotorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_driver::MotorStatus_<ContainerAllocator>& v)
  {
    s << indent << "location[]" << std::endl;
    for (size_t i = 0; i < v.location.size(); ++i)
    {
      s << indent << "  location[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.location[i]);
    }
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.speed[i]);
    }
    s << indent << "load[]" << std::endl;
    for (size_t i = 0; i < v.load.size(); ++i)
    {
      s << indent << "  load[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.load[i]);
    }
    s << indent << "voltage[]" << std::endl;
    for (size_t i = 0; i < v.voltage.size(); ++i)
    {
      s << indent << "  voltage[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.voltage[i]);
    }
    s << indent << "temperature[]" << std::endl;
    for (size_t i = 0; i < v.temperature.size(); ++i)
    {
      s << indent << "  temperature[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.temperature[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current[i]);
    }
    s << indent << "error[]" << std::endl;
    for (size_t i = 0; i < v.error.size(); ++i)
    {
      s << indent << "  error[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.error[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_MOTORSTATUS_H
