// Generated by gencpp from file xarm_driver/SingleJointControl.msg
// DO NOT EDIT!


#ifndef XARM_DRIVER_MESSAGE_SINGLEJOINTCONTROL_H
#define XARM_DRIVER_MESSAGE_SINGLEJOINTCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace xarm_driver
{
template <class ContainerAllocator>
struct SingleJointControl_
{
  typedef SingleJointControl_<ContainerAllocator> Type;

  SingleJointControl_()
    : header()
    , id(0)
    , rad(0.0)  {
    }
  SingleJointControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , rad(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _id_type;
  _id_type id;

   typedef float _rad_type;
  _rad_type rad;





  typedef boost::shared_ptr< ::xarm_driver::SingleJointControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xarm_driver::SingleJointControl_<ContainerAllocator> const> ConstPtr;

}; // struct SingleJointControl_

typedef ::xarm_driver::SingleJointControl_<std::allocator<void> > SingleJointControl;

typedef boost::shared_ptr< ::xarm_driver::SingleJointControl > SingleJointControlPtr;
typedef boost::shared_ptr< ::xarm_driver::SingleJointControl const> SingleJointControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xarm_driver::SingleJointControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xarm_driver::SingleJointControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace xarm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'xarm_driver': ['/home/xbot/catkin_ws/src/xarm/xarm_driver/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xarm_driver::SingleJointControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xarm_driver::SingleJointControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xarm_driver::SingleJointControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81f0959ebd00b7475651c3cbb5d24d85";
  }

  static const char* value(const ::xarm_driver::SingleJointControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81f0959ebd00b747ULL;
  static const uint64_t static_value2 = 0x5651c3cbb5d24d85ULL;
};

template<class ContainerAllocator>
struct DataType< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xarm_driver/SingleJointControl";
  }

  static const char* value(const ::xarm_driver::SingleJointControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8   id\n\
float32   rad\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::xarm_driver::SingleJointControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SingleJointControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xarm_driver::SingleJointControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xarm_driver::SingleJointControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "rad: ";
    Printer<float>::stream(s, indent + "  ", v.rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XARM_DRIVER_MESSAGE_SINGLEJOINTCONTROL_H
